from setuptools import setup, find_packages

setup(
    name="bitcoin_scalper",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.23.5",
        "pandas>=1.5.3",
        "python-dotenv>=1.0.0",
        "streamlit>=1.32.0",
        "scikit-learn>=1.0.0",
        "hmmlearn>=0.2.7",
        "bayesian-optimization>=1.2.0",
        "arch>=5.0.0",
        "optuna>=3.0.0",
        "xgboost>=1.5.0",
        "lightgbm>=3.3.0",
        "matplotlib>=3.7.1",
        "plotly>=5.19.0",
        "seaborn>=0.11.0",
        "SQLAlchemy>=2.0.23",
        "pydantic>=2.5.2",
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "python-multipart>=0.0.6",
        "pytest>=7.4.3",
        "pytest-cov>=5.0.0",
        "pytest-mock>=3.11.1",
        "flake8>=7.0.0",
        "black>=24.1.1",
        "isort>=5.13.2",
        "mypy>=1.8.0",
        "psutil>=5.9.8",
        "loguru>=0.5.3",
        "ta>=0.7.0",
        "requests>=2.26.0",
        "python-telegram-bot>=20.0",
    ],
    python_requires=">=3.9",
    author="Votre Nom",
    author_email="votre.email@example.com",
    description="Un bot de trading algorithmique pour le Bitcoin",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/votre-username/bitcoin-scalper",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
